#!/bin/sh
# Font preview with ueberzug and fzf
# This is inspired by https://github.com/sdushantha/fontpreview

# Checking for environment variables if available.
# These are compatible with original fontpreview.
SIZE=${FONTPREVIEW_SIZE:-800x800}
FONT_SIZE=${FONTPREVIEW_FONT_SIZE:-72}
BG_COLOR=${FONTPREVIEW_BG_COLOR:-#ffffff}
FG_COLOR=${FONTPREVIEW_FG_COLOR:-#000000}
PREVIEW_TEXT=${FONTPREVIEW_PREVIEW_TEXT:-"ABCDEFGHIJKLM\nNOPQRSTUVWXYZ\n\
abcdefghijklm\nnopqrstuvwxyz\n1234567890\n!@#$\%^&*,.;:\n_-=+'\"|\\(){}[]"}

# Ueberzug related variables
FIFO="/tmp/fontpreview-ueberzug-fifo"
IMAGE="/tmp/fontpreview-ueberzug-img.png"
ID="fontpreview-ueberzug"
WIDTH=$FZF_PREVIEW_COLUMNS
HEIGHT=$FZF_PREVIEW_LINES

usage() {
    echo "Usage: fontpreview-ueberzug [-h] [-s FONT_SIZE] [-b BG] [-f FG] [-t TEXT]"
}

start_ueberzug() {
    mkfifo "$FIFO" || exit 1
    touch "$IMAGE" || exit 1
    ueberzug layer --parser json --silent < "$FIFO" &
    # https://github.com/seebye/ueberzug/issues/54#issuecomment-502869935
    exec 3>"$FIFO"
}

stop_ueberzug() {
    exec 3>&-
    rm "$FIFO" "$IMAGE" > /dev/null 2>&1
}

preview() {
    fontfile=$(echo "$1" | cut -f2)
    # In fzf the cols and lines are those of the preview pane
    convert -size "$SIZE" xc:"$BG_COLOR" -fill "$FG_COLOR" \
        -pointsize "$FONT_SIZE" -font "$fontfile" -gravity center \
        -annotate +0+0 "$PREVIEW_TEXT" "$IMAGE" &&
    {   printf '{ "action": "add", "identifier": "%s", "path": "%s",' "$ID" "$IMAGE"
        printf '"x": %d, "y": %d, "scaler": "fit_contain",' 2 1
        printf '"width": %d, "height": %d }\n' "$WIDTH" "$((HEIGHT - 2))"
    } > "$FIFO" ||
    printf '{ "action": "remove", "identifier": "%s" }\n' "$ID" > "$FIFO"
}

while getopts "hs:b:f:t:" arg; do
    case "$arg" in
        s) FONT_SIZE=$OPTARG;;
        b) BG_COLOR=$OPTARG;;
        f) FG_COLOR=$OPTARG;;
        t) PREVIEW_TEXT=$OPTARG;;
        *) usage; exit ;;
    esac
done
shift $((OPTIND - 1))

if [ "$#" = 0 ]; then
    trap stop_ueberzug EXIT QUIT INT TERM
    # Prepare
    start_ueberzug
    # Export cli args as environment variables for preview command
    export FONTPREVIEW_FONT_SIZE="$FONT_SIZE"
    export FONTPREVIEW_BG_COLOR="$BG_COLOR"
    export FONTPREVIEW_FG_COLOR="$FG_COLOR"
    export FONTPREVIEW_PREVIEW_TEXT="$PREVIEW_TEXT"
    # The preview command runs this script again with an argument
    families=$(convert -list font | sed -n 's/ *family: //p' | sort | uniq)
    fc-list -f "%{family}:%{style}:%{file}\n" | sort | uniq |
    while IFS=: read -r family style file; do
        [ "${families%${family%,*}*}" = "$families" ] && continue
        printf "%s%s\t%s\n" "${family%,*}" "${style:+:style=${style%,*}}" "$file"
    done |
    fzf --with-nth 1 --delimiter "\t" --layout=reverse --preview "sh $0 {}" \
        --preview-window "left:50%:noborder:wrap"
elif [ "$#" = 1 ]; then
    [ -p "$FIFO" ] && preview "$1"
fi
